import type { DiscoveredExam } from "./types";

export const DISCOVERED_EXAMS_DATASET: DiscoveredExam[] = [
  // UNICAMP
  {
    id: "unicamp-2025-f1-qconcursos",
    institution: "UNICAMP",
    examName: "UNICAMP 2025 - 1ª Fase",
    year: 2025,
    phase: "1a_fase",
    edition: "Geral",
    variant: "Caderno Q",
    status: "final",
    totalQuestions: 72,
    hasOfficialAnswerKey: true,
    hasExamDocument: true,
    examDocumentUrl: "https://www.comvest.unicamp.br/pv2025/f1/prova_q.pdf",
    answerKeyDocumentUrl: "https://www.comvest.unicamp.br/pv2025/f1/gabarito_q.pdf",
    aggregatorSourceId: "qconcursos",
    discoveredAt: "2026-09-08T10:00:00Z",
    questions: Array.from({ length: 72 }, (_, i) => ({
      questionNumber: i + 1,
      correctAnswer: ["A", "B", "C", "D"][i % 4],
      isAnnulled: i === 14,
      subject: i < 12 ? "Língua Portuguesa" : i < 24 ? "Matemática" : i < 36 ? "História" : i < 48 ? "Geografia" : i < 60 ? "Física" : "Química",
    })),
  },
  {
    id: "unicamp-2025-f1-kuadro",
    institution: "UNICAMP",
    examName: "UNICAMP Vestibular 2025 - Primeira Fase",
    year: 2025,
    phase: "1a_fase",
    edition: "Geral",
    variant: "Caderno Q",
    status: "final",
    totalQuestions: 72,
    hasOfficialAnswerKey: true,
    hasExamDocument: true,
    examDocumentUrl: "https://www.kuadro.com.br/provas/unicamp-2025-1fase.pdf",
    aggregatorSourceId: "kuadro",
    discoveredAt: "2026-09-08T10:05:00Z",
    questions: Array.from({ length: 72 }, (_, i) => ({
      questionNumber: i + 1,
      correctAnswer: ["A", "B", "C", "D"][i % 4],
      isAnnulled: i === 14,
      subject: "Conhecimentos Gerais",
    })),
  },
  {
    id: "unicamp-2024-f1-agatha",
    institution: "UNICAMP",
    examName: "UNICAMP 2024 - 1ª Fase",
    year: 2024,
    phase: "1a_fase",
    edition: "Geral",
    variant: "Caderno R",
    status: "final",
    totalQuestions: 72,
    hasOfficialAnswerKey: true,
    hasExamDocument: true,
    aggregatorSourceId: "projeto-agatha",
    discoveredAt: "2026-09-08T10:10:00Z",
    questions: Array.from({ length: 72 }, (_, i) => ({
      questionNumber: i + 1,
      correctAnswer: ["A", "B", "C", "D"][(i + 1) % 4],
      isAnnulled: false,
    })),
  },
  {
    id: "unicamp-2023-f1-estuda",
    institution: "UNICAMP",
    examName: "UNICAMP 2023 - 1ª Fase",
    year: 2023,
    phase: "1a_fase",
    edition: "Geral",
    status: "final",
    totalQuestions: 72,
    hasOfficialAnswerKey: true,
    hasExamDocument: true,
    aggregatorSourceId: "estuda",
    discoveredAt: "2026-09-08T10:12:00Z",
    questions: Array.from({ length: 72 }, (_, i) => ({
      questionNumber: i + 1,
      correctAnswer: ["A", "B", "C", "D"][(i + 2) % 4],
      isAnnulled: false,
    })),
  },

  // UNESP
  {
    id: "unesp-2025-f1-qconcursos",
    institution: "UNESP",
    examName: "UNESP 2025 - Conhecimentos Gerais",
    year: 2025,
    phase: "1a_fase",
    edition: "Geral",
    variant: "Versão 1",
    status: "final",
    totalQuestions: 90,
    hasOfficialAnswerKey: true,
    hasExamDocument: true,
    examDocumentUrl: "https://www.vunesp.com.br/provas/unesp2025_cg.pdf",
    answerKeyDocumentUrl: "https://www.vunesp.com.br/provas/unesp2025_gab.pdf",
    aggregatorSourceId: "qconcursos",
    discoveredAt: "2026-09-08T10:15:00Z",
    questions: Array.from({ length: 90 }, (_, i) => ({
      questionNumber: i + 1,
      correctAnswer: ["A", "B", "C", "D", "E"][i % 5],
      isAnnulled: i === 30,
    })),
  },
  {
    id: "unesp-2024-f1-etapa",
    institution: "UNESP",
    examName: "UNESP Vestibular 2024 - 1ª Fase",
    year: 2024,
    phase: "1a_fase",
    edition: "Geral",
    status: "final",
    totalQuestions: 90,
    hasOfficialAnswerKey: true,
    hasExamDocument: true,
    aggregatorSourceId: "etapa-resolve",
    discoveredAt: "2026-09-08T10:20:00Z",
    questions: Array.from({ length: 90 }, (_, i) => ({
      questionNumber: i + 1,
      correctAnswer: ["A", "B", "C", "D", "E"][(i + 2) % 5],
      isAnnulled: false,
    })),
  },
  {
    id: "unesp-2023-f1-anglo",
    institution: "UNESP",
    examName: "UNESP Vestibular 2023 - 1ª Fase",
    year: 2023,
    phase: "1a_fase",
    edition: "Geral",
    status: "final",
    totalQuestions: 90,
    hasOfficialAnswerKey: true,
    hasExamDocument: true,
    aggregatorSourceId: "anglo-resolve",
    discoveredAt: "2026-09-08T10:22:00Z",
    questions: Array.from({ length: 90 }, (_, i) => ({
      questionNumber: i + 1,
      correctAnswer: ["A", "B", "C", "D", "E"][(i + 1) % 5],
      isAnnulled: false,
    })),
  },

  // UEM
  {
    id: "uem-2024-inverno-estuda",
    institution: "UEM",
    examName: "UEM Vestibular de Inverno 2024 - Conhecimentos Gerais",
    year: 2024,
    phase: "1a_fase",
    edition: "Inverno",
    status: "final",
    totalQuestions: 40,
    hasOfficialAnswerKey: true,
    hasExamDocument: true,
    aggregatorSourceId: "estuda",
    discoveredAt: "2026-09-08T10:25:00Z",
    questions: Array.from({ length: 40 }, (_, i) => ({
      questionNumber: i + 1,
      correctAnswer: "07",
      isAnnulled: false,
    })),
  },
  {
    id: "uem-2024-verao-educabras",
    institution: "UEM",
    examName: "UEM Vestibular de Verão 2024",
    year: 2024,
    phase: "1a_fase",
    edition: "Verão",
    status: "final",
    totalQuestions: 40,
    hasOfficialAnswerKey: true,
    hasExamDocument: true,
    aggregatorSourceId: "educabras",
    discoveredAt: "2026-09-08T10:30:00Z",
    questions: Array.from({ length: 40 }, (_, i) => ({
      questionNumber: i + 1,
      correctAnswer: "13",
      isAnnulled: false,
    })),
  },

  // UEL
  {
    id: "uel-2025-f1-agatha",
    institution: "UEL",
    examName: "UEL 2025 - Conhecimentos Gerais",
    year: 2025,
    phase: "1a_fase",
    edition: "Geral",
    status: "final",
    totalQuestions: 60,
    hasOfficialAnswerKey: true,
    hasExamDocument: true,
    aggregatorSourceId: "projeto-agatha",
    discoveredAt: "2026-09-08T10:35:00Z",
    questions: Array.from({ length: 60 }, (_, i) => ({
      questionNumber: i + 1,
      correctAnswer: ["A", "B", "C", "D", "E"][i % 5],
      isAnnulled: false,
    })),
  },
  {
    id: "uel-2024-f1-qconcursos",
    institution: "UEL",
    examName: "UEL 2024 - Conhecimentos Gerais",
    year: 2024,
    phase: "1a_fase",
    edition: "Geral",
    status: "final",
    totalQuestions: 60,
    hasOfficialAnswerKey: true,
    hasExamDocument: true,
    aggregatorSourceId: "qconcursos",
    discoveredAt: "2026-09-08T10:37:00Z",
    questions: Array.from({ length: 60 }, (_, i) => ({
      questionNumber: i + 1,
      correctAnswer: ["A", "B", "C", "D", "E"][(i + 3) % 5],
      isAnnulled: false,
    })),
  },

  // UEPG
  {
    id: "uepg-2024-outono-soexercicios",
    institution: "UEPG",
    examName: "UEPG Vestibular de Outono 2024",
    year: 2024,
    phase: "1a_fase",
    edition: "Outono",
    status: "final",
    totalQuestions: 50,
    hasOfficialAnswerKey: true,
    hasExamDocument: true,
    aggregatorSourceId: "so-exercicios",
    discoveredAt: "2026-09-08T10:40:00Z",
    questions: Array.from({ length: 50 }, (_, i) => ({
      questionNumber: i + 1,
      correctAnswer: "15",
      isAnnulled: false,
    })),
  },

  // UFSC
  {
    id: "ufsc-2025-dia1-brasilescola",
    institution: "UFSC",
    examName: "UFSC Vestibular 2025 - Dia 1",
    year: 2025,
    phase: "dia1",
    edition: "Geral",
    status: "final",
    totalQuestions: 40,
    hasOfficialAnswerKey: true,
    hasExamDocument: true,
    aggregatorSourceId: "brasil-escola",
    discoveredAt: "2026-09-08T10:45:00Z",
    questions: Array.from({ length: 40 }, (_, i) => ({
      questionNumber: i + 1,
      correctAnswer: "11",
      isAnnulled: false,
    })),
  },
  {
    id: "ufsc-2024-dia1-kuadro",
    institution: "UFSC",
    examName: "UFSC Vestibular 2024 - Dia 1",
    year: 2024,
    phase: "dia1",
    edition: "Geral",
    status: "final",
    totalQuestions: 40,
    hasOfficialAnswerKey: true,
    hasExamDocument: true,
    aggregatorSourceId: "kuadro",
    discoveredAt: "2026-09-08T10:47:00Z",
    questions: Array.from({ length: 40 }, (_, i) => ({
      questionNumber: i + 1,
      correctAnswer: "09",
      isAnnulled: false,
    })),
  },

  // UDESC
  {
    id: "udesc-2024-verao-kuadro",
    institution: "UDESC",
    examName: "UDESC Vestibular de Verão 2024",
    year: 2024,
    phase: "1a_fase",
    edition: "Verão",
    status: "final",
    totalQuestions: 60,
    hasOfficialAnswerKey: true,
    hasExamDocument: true,
    aggregatorSourceId: "kuadro",
    discoveredAt: "2026-09-08T10:50:00Z",
    questions: Array.from({ length: 60 }, (_, i) => ({
      questionNumber: i + 1,
      correctAnswer: ["A", "B", "C", "D", "E"][i % 5],
      isAnnulled: false,
    })),
  },

  // ACAFE
  {
    id: "acafe-2025-verao-anglo",
    institution: "ACAFE",
    examName: "ACAFE Medicina 2025 - Verão",
    year: 2025,
    phase: "1a_fase",
    edition: "Verão",
    status: "final",
    totalQuestions: 63,
    hasOfficialAnswerKey: true,
    hasExamDocument: true,
    aggregatorSourceId: "anglo-resolve",
    discoveredAt: "2026-09-08T10:55:00Z",
    questions: Array.from({ length: 63 }, (_, i) => ({
      questionNumber: i + 1,
      correctAnswer: ["A", "B", "C", "D"][i % 4],
      isAnnulled: false,
    })),
  },

  // PUC-PR
  {
    id: "pucpr-2025-medicina-bernoulli",
    institution: "PUC-PR",
    examName: "PUC-PR Medicina 2025",
    year: 2025,
    phase: "1a_fase",
    edition: "Geral",
    status: "final",
    totalQuestions: 60,
    hasOfficialAnswerKey: true,
    hasExamDocument: true,
    aggregatorSourceId: "bernoulli-resolve",
    discoveredAt: "2026-09-08T11:00:00Z",
    questions: Array.from({ length: 60 }, (_, i) => ({
      questionNumber: i + 1,
      correctAnswer: ["A", "B", "C", "D", "E"][i % 5],
      isAnnulled: false,
    })),
  },

  // PUC-SP
  {
    id: "pucsp-2024-verao-qconcursos",
    institution: "PUC-SP",
    examName: "PUC-SP Vestibular 2024",
    year: 2024,
    phase: "1a_fase",
    edition: "Verão",
    status: "final",
    totalQuestions: 80,
    hasOfficialAnswerKey: true,
    hasExamDocument: true,
    aggregatorSourceId: "qconcursos",
    discoveredAt: "2026-09-08T11:05:00Z",
    questions: Array.from({ length: 80 }, (_, i) => ({
      questionNumber: i + 1,
      correctAnswer: ["A", "B", "C", "D", "E"][i % 5],
      isAnnulled: false,
    })),
  },

  // PUC-Rio
  {
    id: "pucrio-2025-grupo2-estuda",
    institution: "PUC-Rio",
    examName: "PUC-Rio 2025 - Grupo 2",
    year: 2025,
    phase: "1a_fase",
    edition: "Grupo 2",
    status: "final",
    totalQuestions: 50,
    hasOfficialAnswerKey: true,
    hasExamDocument: true,
    aggregatorSourceId: "estuda",
    discoveredAt: "2026-09-08T11:10:00Z",
    questions: Array.from({ length: 50 }, (_, i) => ({
      questionNumber: i + 1,
      correctAnswer: ["A", "B", "C", "D", "E"][i % 5],
      isAnnulled: false,
    })),
  },

  // Mackenzie
  {
    id: "mackenzie-2025-verao-educabras",
    institution: "Mackenzie",
    examName: "Mackenzie Vestibular 2025 - Verão",
    year: 2025,
    phase: "1a_fase",
    edition: "Verão",
    status: "final",
    totalQuestions: 60,
    hasOfficialAnswerKey: true,
    hasExamDocument: true,
    aggregatorSourceId: "educabras",
    discoveredAt: "2026-09-08T11:15:00Z",
    questions: Array.from({ length: 60 }, (_, i) => ({
      questionNumber: i + 1,
      correctAnswer: ["A", "B", "C", "D", "E"][i % 5],
      isAnnulled: false,
    })),
  },

  // FATEC
  {
    id: "fatec-2025-1sem-qconcursos",
    institution: "FATEC",
    examName: "FATEC 2025 - 1º Semestre",
    year: 2025,
    phase: "1a_fase",
    edition: "1o_semestre",
    status: "final",
    totalQuestions: 54,
    hasOfficialAnswerKey: true,
    hasExamDocument: true,
    aggregatorSourceId: "qconcursos",
    discoveredAt: "2026-09-08T11:20:00Z",
    questions: Array.from({ length: 54 }, (_, i) => ({
      questionNumber: i + 1,
      correctAnswer: ["A", "B", "C", "D", "E"][i % 5],
      isAnnulled: false,
    })),
  },

  // UNIFESP
  {
    id: "unifesp-2024-misto-etapa",
    institution: "UNIFESP",
    examName: "UNIFESP 2024 - Sistema Misto",
    year: 2024,
    phase: "1a_fase",
    edition: "Misto",
    status: "final",
    totalQuestions: 50,
    hasOfficialAnswerKey: true,
    hasExamDocument: true,
    aggregatorSourceId: "etapa-resolve",
    discoveredAt: "2026-09-08T11:25:00Z",
    questions: Array.from({ length: 50 }, (_, i) => ({
      questionNumber: i + 1,
      correctAnswer: ["A", "B", "C", "D", "E"][(i + 1) % 5],
      isAnnulled: false,
    })),
  },

  // FAMERP
  {
    id: "famerp-2025-conhecimentos-gerais-anglo",
    institution: "FAMERP",
    examName: "FAMERP Medicina 2025 - Conhecimentos Gerais",
    year: 2025,
    phase: "1a_fase",
    edition: "Geral",
    status: "final",
    totalQuestions: 80,
    hasOfficialAnswerKey: true,
    hasExamDocument: true,
    aggregatorSourceId: "anglo-resolve",
    discoveredAt: "2026-09-08T11:30:00Z",
    questions: Array.from({ length: 80 }, (_, i) => ({
      questionNumber: i + 1,
      correctAnswer: ["A", "B", "C", "D", "E"][i % 5],
      isAnnulled: false,
    })),
  },

  // UFRGS
  {
    id: "ufrgs-2025-dia1-estuda",
    institution: "UFRGS",
    examName: "UFRGS Vestibular 2025 - Dia 1",
    year: 2025,
    phase: "dia1",
    edition: "Geral",
    status: "final",
    totalQuestions: 75,
    hasOfficialAnswerKey: true,
    hasExamDocument: true,
    aggregatorSourceId: "estuda",
    discoveredAt: "2026-09-08T11:35:00Z",
    questions: Array.from({ length: 75 }, (_, i) => ({
      questionNumber: i + 1,
      correctAnswer: ["A", "B", "C", "D", "E"][(i + 2) % 5],
      isAnnulled: false,
    })),
  },

  // UERJ
  {
    id: "uerj-2025-eq1-projetoagatha",
    institution: "UERJ",
    examName: "UERJ 2025 - 1º Exame de Qualificação",
    year: 2025,
    phase: "eq1",
    edition: "Geral",
    status: "final",
    totalQuestions: 60,
    hasOfficialAnswerKey: true,
    hasExamDocument: true,
    aggregatorSourceId: "projeto-agatha",
    discoveredAt: "2026-09-08T11:40:00Z",
    questions: Array.from({ length: 60 }, (_, i) => ({
      questionNumber: i + 1,
      correctAnswer: ["A", "B", "C", "D"][i % 4],
      isAnnulled: false,
    })),
  },

  // UFPR
  {
    id: "ufpr-2025-f1-kuadro",
    institution: "UFPR",
    examName: "UFPR Processo Seletivo 2025 - 1ª Fase",
    year: 2025,
    phase: "1a_fase",
    edition: "Geral",
    status: "final",
    totalQuestions: 90,
    hasOfficialAnswerKey: true,
    hasExamDocument: true,
    aggregatorSourceId: "kuadro",
    discoveredAt: "2026-09-08T11:45:00Z",
    questions: Array.from({ length: 90 }, (_, i) => ({
      questionNumber: i + 1,
      correctAnswer: ["A", "B", "C", "D", "E"][i % 5],
      isAnnulled: false,
    })),
  },
];
